/**
 * yarn.lock adapter — parse yarn v1 classic + Berry (`__metadata`) into
 * LockfilePackage[], plus a scan integration over a real yarn project.
 *
 * Mirrors the pnpm adapter's test shape (test/pnpm.test.ts): real samples live
 * under testdata/ and are read at test time; the parser contract and the known
 * yarn information loss (no hasInstallScript) are asserted explicitly.
 */
import { describe, expect, it } from 'vitest'
import { parseYarnLockfile } from '../src/adapters/node/yarn'
import { scan } from '../src/adapters/node/pipeline'
import type { Environment } from '../src/core/model'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { readFileSync } from 'node:fs'

const env: Environment = {
  os: 'linux',
  arch: 'x64',
  libc: 'glibc',
  nodeVersion: '22.22.2',
  nodeAbi: '127',
  python: { version: '3.12.4' },
  compiler: { name: 'gcc', cProbe: true, cxxProbe: true },
  sdks: [],
}

const testdata = join(fileURLToPath(new URL('.', import.meta.url)), '..', 'testdata')

/** Minimal real yarn v1 excerpt with an optional platform cluster. */
const V1_SAMPLE = `# yarn lockfile v1

"@esbuild/linux-x64@0.19.12":
  version "0.19.12"
  resolved "https://registry.yarnpkg.com/@esbuild/linux-x64/-/linux-x64-0.19.12.tgz"
  integrity sha512-hKoVkKzFiToTgn+41qGhsUJXFlIjxI/jSYeZf3ugemDYZldIXIxhvwN6erJGlX4t5h417iFuheZ7l+YVn05N3A==

esbuild@^0.19.0:
  version "0.19.12"
  resolved "https://registry.yarnpkg.com/esbuild/-/esbuild-0.19.12.tgz"
  optionalDependencies:
    "@esbuild/linux-x64" "0.19.12"
    "@esbuild/win32-x64" "0.19.12"

better-sqlite3@^11.0.0:
  version "11.10.0"
  resolved "https://registry.yarnpkg.com/better-sqlite3/-/better-sqlite3-11.10.0.tgz"
  dependencies:
    bindings "^1.5.0"
    prebuild-install "^7.1.1"
`

/** Minimal real Yarn Berry excerpt with a dependency edge. */
const BERRY_SAMPLE = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@esbuild/linux-x64@npm:0.19.12":
  version: 0.19.12
  resolution: "@esbuild/linux-x64@npm:0.19.12"
  conditions: os=linux & cpu=x64
  languageName: node
  linkType: hard

"better-sqlite3@npm:^11.0.0":
  version: 11.10.0
  resolution: "better-sqlite3@npm:11.10.0"
  dependencies:
    bindings: "npm:^1.5.0"
    node-gyp: "npm:latest"
    prebuild-install: "npm:^7.1.1"
  languageName: node
  linkType: hard
`

describe('parseYarnLockfile (v1 classic)', () => {
  it('解析顶层 entry + optional 平台簇（Pattern A 信号）', () => {
    const list = parseYarnLockfile(V1_SAMPLE)
    const byName = new Map(list.map((p) => [p.name, p]))

    expect(list.length).toBe(3)
    const esbuild = byName.get('esbuild')
    expect(esbuild?.version).toBe('0.19.12')
    // optionalDependencies 边标记为 optional → classify 判 Pattern A。
    expect(esbuild?.dependencies?.['@esbuild/linux-x64']?.optional).toBe(true)

    const bs = byName.get('better-sqlite3')
    expect(bs?.dependencies?.['bindings']).toEqual({ name: 'bindings' })
    expect(bs?.dependencies?.['prebuild-install']).toEqual({ name: 'prebuild-install' })
    // yarn 不记录 install 脚本。
    expect(bs?.hasInstallScript).toBe(false)
  })

  it('空 / 非 lockfile → 空列表（Fail Closed）', () => {
    expect(parseYarnLockfile('')).toEqual([])
    expect(parseYarnLockfile('not a lockfile at all')).toEqual([])
  })
})

describe('parseYarnLockfile (Berry __metadata)', () => {
  it('解析 Berry entry + dependencies 边', () => {
    const list = parseYarnLockfile(BERRY_SAMPLE)
    const byName = new Map(list.map((p) => [p.name, p]))

    const bs = byName.get('better-sqlite3')
    expect(bs?.version).toBe('11.10.0')
    expect(bs?.dependencies?.['node-gyp']).toEqual({ name: 'node-gyp' })
    expect(bs?.dependencies?.['prebuild-install']).toEqual({ name: 'prebuild-install' })

    // Berry 平台包用独立 entry（conditions），不是 optional 边 → 无 Pattern A 边。
    const platform = byName.get('@esbuild/linux-x64')
    expect(platform?.version).toBe('0.19.12')
  })

  it('别名键（alias@npm:real@range）解析为真实包名', () => {
    // Berry 把别名写成 `"my-alias@npm:node-pty@^1.0.0"`，entry 描述的是 node-pty
    // （tarball、install 脚本、构建工具依赖都来自它）。不剥别名壳的话，name 会变成
    // `my-alias@npm:node-pty`，所有按包名查表的规则都会失效。
    const list = parseYarnLockfile(`__metadata:
  version: 8

"node-pty@npm:^1.0.0":
  version: 1.1.0

"my-alias@npm:node-pty@^1.0.0":
  version: 1.1.0
`)
    expect(list.map((p) => p.name)).toEqual(['node-pty', 'node-pty'])
    expect(list.map((p) => p.version)).toEqual(['1.1.0', '1.1.0'])
  })
})

describe('yarn 集成 · scan 真实 yarn.lock（零网络）', () => {
  it('yarn v1：esbuild → Pattern A，better-sqlite3 → Pattern C', async () => {
    const { report, unsupported } = await scan(join(testdata, 'yarn-v1'), {
      mode: 'fast',
      env,
    })
    expect(unsupported).toBeUndefined()
    expect(report.summary.networkCalls).toBe(0)
    expect(report.summary.totalPackages).toBeGreaterThanOrEqual(40)

    const esbuild = report.findings.find((f) => f.pkg.name === 'esbuild')
    expect(esbuild?.pattern).toBe('PlatformOptionalDeps')
    expect(esbuild?.risk).toBe('LOW')

    const bs = report.findings.find((f) => f.pkg.name === 'better-sqlite3')
    expect(bs?.pattern).toBe('RemoteDownload')
  })

  it('yarn berry：better-sqlite3 依赖边仍在（C），esbuild 无 optional 簇信号', async () => {
    const { report, unsupported } = await scan(join(testdata, 'yarn-berry'), {
      mode: 'fast',
      env,
    })
    expect(unsupported).toBeUndefined()
    expect(report.summary.networkCalls).toBe(0)

    // Berry lockfile 保留 dependencies 边 → better-sqlite3 仍是 C。
    const bs = report.findings.find((f) => f.pkg.name === 'better-sqlite3')
    expect(bs?.pattern).toBe('RemoteDownload')

    // Berry 无 optionalDependencies → esbuild 型 Pattern A 在 berry 下不出现。
    // 这是 berry lockfile 的信息限制（文档化），非误报。
    const esbuild = report.findings.find((f) => f.pkg.name === 'esbuild')
    expect(esbuild).toBeUndefined()
  })

  it('真实 v1 项目 sample 能被 parser 完整读取（防空跑）', () => {
    const real = readFileSync(join(testdata, 'yarn-v1', 'yarn.lock'), 'utf8')
    const list = parseYarnLockfile(real)
    expect(list.length).toBeGreaterThan(30)
    expect(list.some((p) => p.name === 'esbuild')).toBe(true)
  })
})
