/**
 * yarn.lock adapter — parse yarn v1 classic + Berry (`__metadata`) into
 * LockfilePackage[], plus a scan integration over a real yarn project.
 *
 * Mirrors the pnpm adapter's test shape (test/pnpm.test.ts): real samples live
 * under testdata/ and are read at test time; the parser contract and the known
 * yarn information loss (no hasInstallScript) are asserted explicitly.
 */
import { describe, expect, it } from 'vitest'
import { parseYarnLockfile } from '../src/adapters/node/yarn'
import { scan } from '../src/adapters/node/pipeline'
import type { Environment } from '../src/core/model'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { readFileSync } from 'node:fs'

const env: Environment = {
  os: 'linux',
  arch: 'x64',
  libc: 'glibc',
  nodeVersion: '22.22.2',
  nodeAbi: '127',
  python: { version: '3.12.4' },
  compiler: { name: 'gcc', cProbe: true, cxxProbe: true },
  sdks: [],
}

const testdata = join(fileURLToPath(new URL('.', import.meta.url)), '..', 'testdata')

/** Minimal real yarn v1 excerpt with an optional platform cluster. */
const V1_SAMPLE = `# yarn lockfile v1

"@esbuild/linux-x64@0.19.12":
  version "0.19.12"
  resolved "https://registry.yarnpkg.com/@esbuild/linux-x64/-/linux-x64-0.19.12.tgz"
  integrity sha512-hKoVkKzFiToTgn+41qGhsUJXFlIjxI/jSYeZf3ugemDYZldIXIxhvwN6erJGlX4t5h417iFuheZ7l+YVn05N3A==

esbuild@^0.19.0:
  version "0.19.12"
  resolved "https://registry.yarnpkg.com/esbuild/-/esbuild-0.19.12.tgz"
  optionalDependencies:
    "@esbuild/linux-x64" "0.19.12"
    "@esbuild/win32-x64" "0.19.12"

better-sqlite3@^11.0.0:
  version "11.10.0"
  resolved "https://registry.yarnpkg.com/better-sqlite3/-/better-sqlite3-11.10.0.tgz"
  dependencies:
    bindings "^1.5.0"
    prebuild-install "^7.1.1"
`

/** Minimal real Yarn Berry excerpt with a dependency edge. */
const BERRY_SAMPLE = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@esbuild/linux-x64@npm:0.19.12":
  version: 0.19.12
  resolution: "@esbuild/linux-x64@npm:0.19.12"
  conditions: os=linux & cpu=x64
  languageName: node
  linkType: hard

"better-sqlite3@npm:^11.0.0":
  version: 11.10.0
  resolution: "better-sqlite3@npm:11.10.0"
  dependencies:
    bindings: "npm:^1.5.0"
    node-gyp: "npm:latest"
    prebuild-install: "npm:^7.1.1"
  languageName: node
  linkType: hard
`

describe('parseYarnLockfile (v1 classic)', () => {
  it('parses top-level entries + the optional platform cluster (pattern A signal)', () => {
    const list = parseYarnLockfile(V1_SAMPLE)
    const byName = new Map(list.map((p) => [p.name, p]))

    expect(list.length).toBe(3)
    const esbuild = byName.get('esbuild')
    expect(esbuild?.version).toBe('0.19.12')
    // optionalDependencies edges are marked optional → classify reports pattern A.
    expect(esbuild?.dependencies?.['@esbuild/linux-x64']?.optional).toBe(true)

    const bs = byName.get('better-sqlite3')
    expect(bs?.dependencies?.['bindings']).toEqual({ name: 'bindings' })
    expect(bs?.dependencies?.['prebuild-install']).toEqual({ name: 'prebuild-install' })
    // yarn records no install scripts, so the flag must stay `false` here: the
    // adapter has no equivalent field to read (pnpm has requiresBuild, yarn has
    // nothing), and `undefined` would be read as "unknown" downstream.
    expect(bs?.hasInstallScript).toBe(false)
  })

  it('empty / not a lockfile → empty list (fail closed)', () => {
    expect(parseYarnLockfile('')).toEqual([])
    expect(parseYarnLockfile('not a lockfile at all')).toEqual([])
  })
})

describe('parseYarnLockfile (Berry __metadata)', () => {
  it('parses Berry entries + dependency edges', () => {
    const list = parseYarnLockfile(BERRY_SAMPLE)
    const byName = new Map(list.map((p) => [p.name, p]))

    const bs = byName.get('better-sqlite3')
    expect(bs?.version).toBe('11.10.0')
    expect(bs?.dependencies?.['node-gyp']).toEqual({ name: 'node-gyp' })
    expect(bs?.dependencies?.['prebuild-install']).toEqual({ name: 'prebuild-install' })

    // Berry platform packages use their own entries (conditions), not optional edges,
    const platform = byName.get('@esbuild/linux-x64')
    expect(platform?.version).toBe('0.19.12')
  })

  it('an alias key (alias@npm:real@range) resolves to the real package name', () => {
    // Berry writes aliases as `"my-alias@npm:node-pty@^1.0.0"`, and the entry describes
    // node-pty itself (tarball, install script, build-tool dependencies all come from it).
    // Leaving the alias shell on would yield `my-alias@npm:node-pty`, and every rule that
    const list = parseYarnLockfile(`__metadata:
  version: 8

"node-pty@npm:^1.0.0":
  version: 1.1.0

"my-alias@npm:node-pty@^1.0.0":
  version: 1.1.0
`)
    expect(list.map((p) => p.name)).toEqual(['node-pty', 'node-pty'])
    expect(list.map((p) => p.version)).toEqual(['1.1.0', '1.1.0'])
  })
})

describe('yarn integration · scan against a real yarn.lock (zero network)', () => {
  it('yarn v1：esbuild → Pattern A，better-sqlite3 → Pattern C', async () => {
    const { report, unsupported } = await scan(join(testdata, 'yarn-v1'), {
      mode: 'fast',
      env,
    })
    expect(unsupported).toBeUndefined()
    expect(report.summary.networkCalls).toBe(0)
    expect(report.summary.totalPackages).toBeGreaterThanOrEqual(40)

    const esbuild = report.findings.find((f) => f.pkg.name === 'esbuild')
    expect(esbuild?.pattern).toBe('PlatformOptionalDeps')
    expect(esbuild?.risk).toBe('LOW')

    const bs = report.findings.find((f) => f.pkg.name === 'better-sqlite3')
    expect(bs?.pattern).toBe('RemoteDownload')
  })

  it('yarn berry: better-sqlite3 keeps its dependency edge (C), esbuild has no optional cluster', async () => {
    const { report, unsupported } = await scan(join(testdata, 'yarn-berry'), {
      mode: 'fast',
      env,
    })
    expect(unsupported).toBeUndefined()
    expect(report.summary.networkCalls).toBe(0)

    // The Berry lockfile keeps dependency edges → better-sqlite3 is still C.
    const bs = report.findings.find((f) => f.pkg.name === 'better-sqlite3')
    expect(bs?.pattern).toBe('RemoteDownload')

    // Berry has no optionalDependencies → an esbuild-style pattern A cannot appear.
    // That is a documented limit of the Berry lockfile, not a false positive.
    const esbuild = report.findings.find((f) => f.pkg.name === 'esbuild')
    expect(esbuild).toBeUndefined()
  })

  it('a real v1 project sample parses completely (guards against a no-op parser)', () => {
    const real = readFileSync(join(testdata, 'yarn-v1', 'yarn.lock'), 'utf8')
    const list = parseYarnLockfile(real)
    expect(list.length).toBeGreaterThan(30)
    expect(list.some((p) => p.name === 'esbuild')).toBe(true)
  })
})
